# site settings
title: Mara Dimofte
email: mara.dimofte@columbia.edu
description: I am a junior at Columbia University in love with tech and art!
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://maradimo.github.io"# the base hostname & protocol for your site

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 2

# social settings
500px_url:
facebook_url:
google_url: https://www.engineering.columbia.edu/egleston-scholars/mara-dimofte
linkedin_url: https://www.linkedin.com/in/mara-dimofte-797779174/
github_url: https://github.com/maradimo
pinterest_url:
slack_url:
<<<<<<< HEAD
twitter_url: https://twitter.com/andrewbanchich
=======

url: "https://maradimo.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  maradimo

>>>>>>> 513d1ddf6889d68e1efb3cb76a2f8b3b39fec85f

# build settings
markdown: kramdown

sass:
  style: compressed
